enabled: true

exclude:
  - "**/*.patch"
  - ".github/workflows/**/*"

changed_paths:
  maximum: 1000
  outcome: error

remote_files: []

auto: false

commit_template: |
  Restyled by ${restyler.name}

pull_requests: true

comments: false

statuses:
  differences: true
  no_differences: true
  error: true

request_review: none

labels:
  - restyle

ignore_labels:
  - restyled-ignore

restylers_version: stable

restylers:
  - google-java-format
  - prettier-markdown
  - prettier-yaml
  - whitespace
  -